window["distri/ash:master"]({
  "source": {
    "LICENSE": {
      "path": "LICENSE",
      "mode": "100644",
      "content": "The MIT License (MIT)\n\nCopyright (c) 2014 distri\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of\nthis software and associated documentation files (the \"Software\"), to deal in\nthe Software without restriction, including without limitation the rights to\nuse, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of\nthe Software, and to permit persons to whom the Software is furnished to do so,\nsubject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS\nFOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR\nCOPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER\nIN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN\nCONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n",
      "type": "blob"
    },
    "README.md": {
      "path": "README.md",
      "mode": "100644",
      "content": "ash\n===\n\nAshes to ashes.\n\nA shell for the browser environment.\n\nExecute \"commands\" inside iframes or child windows.\n\nDisplay interactive html output from commands.\n\nPipes\n-----\n\nPipe data between subprocesses.\n\nPragmatically data is any JS object that can be passed through postMessage.\n",
      "type": "blob"
    }
  },
  "distribution": {},
  "progenitor": {
    "url": "http://strd6.github.io/editor/"
  },
  "entryPoint": "main",
  "repository": {
    "id": 17328123,
    "name": "ash",
    "full_name": "distri/ash",
    "owner": {
      "login": "distri",
      "id": 6005125,
      "avatar_url": "https://avatars.githubusercontent.com/u/6005125",
      "gravatar_id": null,
      "url": "https://api.github.com/users/distri",
      "html_url": "https://github.com/distri",
      "followers_url": "https://api.github.com/users/distri/followers",
      "following_url": "https://api.github.com/users/distri/following{/other_user}",
      "gists_url": "https://api.github.com/users/distri/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/distri/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/distri/subscriptions",
      "organizations_url": "https://api.github.com/users/distri/orgs",
      "repos_url": "https://api.github.com/users/distri/repos",
      "events_url": "https://api.github.com/users/distri/events{/privacy}",
      "received_events_url": "https://api.github.com/users/distri/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/distri/ash",
    "description": "Ashes to ashes",
    "fork": false,
    "url": "https://api.github.com/repos/distri/ash",
    "forks_url": "https://api.github.com/repos/distri/ash/forks",
    "keys_url": "https://api.github.com/repos/distri/ash/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/distri/ash/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/distri/ash/teams",
    "hooks_url": "https://api.github.com/repos/distri/ash/hooks",
    "issue_events_url": "https://api.github.com/repos/distri/ash/issues/events{/number}",
    "events_url": "https://api.github.com/repos/distri/ash/events",
    "assignees_url": "https://api.github.com/repos/distri/ash/assignees{/user}",
    "branches_url": "https://api.github.com/repos/distri/ash/branches{/branch}",
    "tags_url": "https://api.github.com/repos/distri/ash/tags",
    "blobs_url": "https://api.github.com/repos/distri/ash/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/distri/ash/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/distri/ash/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/distri/ash/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/distri/ash/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/distri/ash/languages",
    "stargazers_url": "https://api.github.com/repos/distri/ash/stargazers",
    "contributors_url": "https://api.github.com/repos/distri/ash/contributors",
    "subscribers_url": "https://api.github.com/repos/distri/ash/subscribers",
    "subscription_url": "https://api.github.com/repos/distri/ash/subscription",
    "commits_url": "https://api.github.com/repos/distri/ash/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/distri/ash/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/distri/ash/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/distri/ash/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/distri/ash/contents/{+path}",
    "compare_url": "https://api.github.com/repos/distri/ash/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/distri/ash/merges",
    "archive_url": "https://api.github.com/repos/distri/ash/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/distri/ash/downloads",
    "issues_url": "https://api.github.com/repos/distri/ash/issues{/number}",
    "pulls_url": "https://api.github.com/repos/distri/ash/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/distri/ash/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/distri/ash/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/distri/ash/labels{/name}",
    "releases_url": "https://api.github.com/repos/distri/ash/releases{/id}",
    "created_at": "2014-03-02T00:58:38Z",
    "updated_at": "2014-03-02T00:58:38Z",
    "pushed_at": "2014-03-02T00:58:38Z",
    "git_url": "git://github.com/distri/ash.git",
    "ssh_url": "git@github.com:distri/ash.git",
    "clone_url": "https://github.com/distri/ash.git",
    "svn_url": "https://github.com/distri/ash",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "master_branch": "master",
    "permissions": {
      "admin": true,
      "push": true,
      "pull": true
    },
    "organization": {
      "login": "distri",
      "id": 6005125,
      "avatar_url": "https://avatars.githubusercontent.com/u/6005125",
      "gravatar_id": null,
      "url": "https://api.github.com/users/distri",
      "html_url": "https://github.com/distri",
      "followers_url": "https://api.github.com/users/distri/followers",
      "following_url": "https://api.github.com/users/distri/following{/other_user}",
      "gists_url": "https://api.github.com/users/distri/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/distri/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/distri/subscriptions",
      "organizations_url": "https://api.github.com/users/distri/orgs",
      "repos_url": "https://api.github.com/users/distri/repos",
      "events_url": "https://api.github.com/users/distri/events{/privacy}",
      "received_events_url": "https://api.github.com/users/distri/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "network_count": 0,
    "subscribers_count": 2,
    "branch": "master",
    "publishBranch": "gh-pages"
  },
  "dependencies": {}
});